server {
    listen 8080;
    server_name server0;
    root www;
    index index.html;
}

server {
    listen 8081;
    server_name server1;
    root www2;
    index index.html;
    client_max_body_size 50000000;
}